"""conversation history

Revision ID: 31c0a9d5e318
Revises: 5f3424f20445
Created: 2026-07-28 21:12:44.787062
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "31c0a9d5e318"
down_revision: str | None = "5f3424f20445"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_messages",
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("tool_calls", sa.JSON(), nullable=True),
        sa.Column("tool_call_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("tainted", sa.Boolean(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("principal_id", "seq"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("conversation_messages")
    # ### end Alembic commands ###
