"""The schema as it stood when migrations were introduced.

Everything the product had accumulated by this point, captured in one revision
rather than reconstructed as a fictional history. There is no honest way to
write the twelve migrations that "would have" produced this, and inventing them
would give operators a set of upgrade paths nobody has ever run.

An existing pre-migration deployment does not run this. It runs
``uione-db stamp``, which records that its schema is already here — running the
upgrade would try to create tables that exist and fail on the first one.

**On the downgrade.** It drops every table, which is to say it destroys the audit
log, the approval history and the undo journal. That is the truthful downgrade
for an initial revision and it is why the CLI has no downgrade command: an
operator who needs to go back restores a backup, which is a decision someone
makes deliberately rather than a flag they pass by accident.

Revision ID: 5f3424f20445
Revises:
Created: 2026-07-28 10:45:11.507292
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "5f3424f20445"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_journal",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("tool", sa.String(length=255), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("risk", sa.String(length=32), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("undo_tool", sa.String(length=255), nullable=True),
        sa.Column("undo_arguments", sa.JSON(), nullable=True),
        sa.Column("undone", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("action_journal", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_action_journal_at"), ["at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_action_journal_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("server", sa.String(length=128), nullable=False),
        sa.Column("tool", sa.String(length=255), nullable=False),
        sa.Column("risk", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_log_correlation_id"), ["correlation_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_log_outcome"), ["outcome"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_log_principal_id"), ["principal_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_audit_log_risk"), ["risk"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_log_tool"), ["tool"], unique=False)
        batch_op.create_index(
            "ix_audit_principal_time", ["principal_id", "timestamp"], unique=False
        )
        batch_op.create_index("ix_audit_risk_time", ["risk", "timestamp"], unique=False)

    op.create_table(
        "autonomy_records",
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("tool", sa.String(length=255), nullable=False),
        sa.Column("approvals", sa.Integer(), nullable=False),
        sa.Column("rejections", sa.Integer(), nullable=False),
        sa.Column("consecutive_approvals", sa.Integer(), nullable=False),
        sa.Column("auto_granted", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("principal_id", "tool"),
    )
    op.create_table(
        "disclosure_contracts",
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("default_facets", sa.JSON(), nullable=False),
        sa.Column("external_facets", sa.JSON(), nullable=False),
        sa.Column("by_role", sa.JSON(), nullable=False),
        sa.Column("by_user", sa.JSON(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("owner_id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=512), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("acl_users", sa.JSON(), nullable=False),
        sa.Column("acl_groups", sa.JSON(), nullable=False),
        sa.Column("acl_denied", sa.JSON(), nullable=False),
        sa.Column("acl_visibility", sa.String(length=32), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("doc_metadata", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_documents_source"), ["source"], unique=False)

    op.create_table(
        "embeddings",
        sa.Column("document_id", sa.String(length=512), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("vector", sa.JSON(), nullable=False),
        sa.Column("dims", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("document_id", "model"),
    )
    op.create_table(
        "mcp_pins",
        sa.Column("server", sa.String(length=128), nullable=False),
        sa.Column("tools", sa.JSON(), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_by", sa.String(length=255), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("server"),
    )
    op.create_table(
        "metric_points",
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("metric", sa.String(length=128), nullable=False),
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("principal_id", "metric", "day"),
    )
    op.create_table(
        "pending_actions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("tool", sa.String(length=255), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("risk", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("preview", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pending_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_pending_actions_principal_id"), ["principal_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_pending_actions_status"), ["status"], unique=False)

    op.create_table(
        "schedules",
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("at", sa.String(length=8), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("days", sa.JSON(), nullable=False),
        sa.Column("jitter_s", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=True),
        sa.Column("runs", sa.Integer(), nullable=False),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("principal_id", "kind"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("roles", sa.JSON(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("refresh_token", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_expires_at"), ["expires_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sessions_principal_id"), ["principal_id"], unique=False
        )

    op.create_table(
        "sync_watermarks",
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("last_sync", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_watermarks")
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_principal_id"))
        batch_op.drop_index(batch_op.f("ix_sessions_expires_at"))

    op.drop_table("sessions")
    op.drop_table("schedules")
    with op.batch_alter_table("pending_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pending_actions_status"))
        batch_op.drop_index(batch_op.f("ix_pending_actions_principal_id"))

    op.drop_table("pending_actions")
    op.drop_table("metric_points")
    op.drop_table("mcp_pins")
    op.drop_table("embeddings")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_documents_source"))

    op.drop_table("documents")
    op.drop_table("disclosure_contracts")
    op.drop_table("autonomy_records")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_risk_time")
        batch_op.drop_index("ix_audit_principal_time")
        batch_op.drop_index(batch_op.f("ix_audit_log_tool"))
        batch_op.drop_index(batch_op.f("ix_audit_log_risk"))
        batch_op.drop_index(batch_op.f("ix_audit_log_principal_id"))
        batch_op.drop_index(batch_op.f("ix_audit_log_outcome"))
        batch_op.drop_index(batch_op.f("ix_audit_log_correlation_id"))

    op.drop_table("audit_log")
    with op.batch_alter_table("action_journal", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_action_journal_principal_id"))
        batch_op.drop_index(batch_op.f("ix_action_journal_at"))

    op.drop_table("action_journal")
    # ### end Alembic commands ###
