"""inbound messages

Revision ID: 293397191fe9
Revises: 31c0a9d5e318
Created: 2026-07-29 10:46:21.820323
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision: str = '293397191fe9'
down_revision: str | None = '31c0a9d5e318'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbound_messages',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('principal_id', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=64), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbound_messages_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_inbound_messages_principal_id'), ['principal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbound_messages_principal_id'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_channel'))
        batch_op.drop_index(batch_op.f('ix_inbound_messages_at'))

    op.drop_table('inbound_messages')
    # ### end Alembic commands ###
